### ISSUE TITLE
credentials:"cors" not in spec

### ISSUE THREAD

**Issue by wereHamster** [github/fetch#109]
```
dictionary RequestInit {
  // ...
  RequestMode mode;
  RequestCredentials credentials;
};

enum RequestMode { "same-origin", "no-cors", "cors" };
enum RequestCredentials { "omit", "same-origin", "include" };
```

You can use `{ mode: "cors" }` or `{ credentials: "include" }` but not `{ credentials: "cors" }`. I got confused why my code was not working because I was coding against the spec but then looked through the fetch.js source and saw that it is not compliant ;)

**Comment by chromakode** [comment]
Just got bit by this one too. I think that [this check](https://github.com/github/fetch/blob/89b449384fe7e1858615d2ecf85c78802815d7bb/fetch.js#L264) should check `self.credentials === 'include'` instead of `'cors'`.

**Comment by irvinebroque** [comment]
This issue is causing me pain too:

`credentials: 'cors',` works in browsers that have not yet implemented `fetch()`, but fails in Chrome Canary.
`credentials: 'include',` is spec-compliant, and works in Chrome Canary, but fails in all other browsers.

Are there blockers to getting either #113 or #97 merged in? Happy to help, but it seems like both PRs are stalled and it's unclear why.

**Comment by dgraham** [comment]
This was introduced in #77. It's possible the spec changed since then. @matthew-andrews, any ideas on this?

**Comment by alayor** [comment]
I'm having trouble with this site: http://www.greatapp.xyz/register
I receive XSRF-TOKEN but the Cookie it's not being set in Chrome.
I'm using `credentials: 'include'`
