### ISSUE TITLE
Readme isn't clear about promise polyfill

### ISSUE THREAD

**Issue by callumlocke** [github/fetch#126]
The readme says you just need to do `bower install es6-promise`, but I'm guessing you also need to `require('es6-promise').polyfill();`?

**Comment by mislav** [comment]
Depends. At GitHub, we're loading the es6-promise v1.0 version which doesn't need an explicit call. However, in the v2.0 version the explicit `polyfill()` call is necessary. In the v2.1 version, the call won't be necessary anymore (I haven't verified this).

See https://github.com/github/fetch/issues/114#issuecomment-89342951 https://github.com/jakearchibald/es6-promise/issues/75

@dgraham We definitely need a documentation update to address this, since people right now are mostly on es6-promise 2.0 (their version 2.1 is just fresh out of the oven).

**Comment by dgraham** [comment]
Closing as stale. It's possible the `es6-polyfill` has been fixed by now. If not, a pull request updating the documentation is welcome.
