### ISSUE TITLE
Allow forcing polyfill 

### ISSUE THREAD

**Issue by tjwudi** [github/fetch#147]
I found a bug in Chrome that window.fetch does not send cookie when POSTing, even have credentials set (see [Issue 490519](https://code.google.com/p/chromium/issues/detail?id=490519)). So we may have to polyfill chrome as well, at least provide a way to do so.

Currently **github/fetch** only polyfills UA whose `window.fetch` is undefined. So it will not polyfill the broken `fetch` in chrome.

**Comment by domenic** [comment]
That's not a big, that's per-spec.

**Comment by tjwudi** [comment]
But this polyfill sets `withCredential` to **true**, which sends cookie. Also, firefox sends cookie as well.

**Comment by domenic** [comment]
Your linked example doesnt set with credentials (don't forget the trailing s)

**Comment by domenic** [comment]
Sorry, I was on mobile and not being clear.

Your linked example does not include the `{ credentials: "include" }` option, which (per spec) is required if you want to send cookies. So Chrome's behavior is correct; Firefox's is not, presumably because the polyfill is incorrect, and the polyfill is being used in Firefox.

In general, when two browsers disagree, it is better to check the spec, and file a bug on the browser that doesn't match the spec, instead of filing a bug on the browser whose behavior doesn't match what you _wish_ were standard.

If anything, the bug here is that the fetch polyfill needs to strip out Cookie headers (if that's possible) when not setting `{ credentials: "include" }`.

**Comment by tjwudi** [comment]
@domenic I am sorry I made a mistake there. This fetch is actually a wrapper I wrote, which applies credentials: "include" by default. IT IS A BUG OF CHROME!

**Comment by mislav** [comment]
@tjwudi Can you explain what is a bug of Chrome, i.e. how does it fail to conform to the fetch spec?

Bear in mind that something can be a bug in our implementation as well. Just because Chrome and this polyfill differ, it doesn't mean that Chrome necessarily has a bug.

Did you try using `credentials: 'same-origin'`?

**Comment by tjwudi** [comment]
Hi @mislav 

`fetch` in Chrome fails to send cookie when POSTing with `credentials: include` set. 

In the polyfill, when credentials is set to `"include"`, it will set `withCredentials` to true, which is the expected behavior. See [this line](https://github.com/github/fetch/blob/master/fetch.js#L317).

My Chrome Version 43.0.2357.65 (64-bit)

**Comment by domenic** [comment]
I mean, that's just not true. We have many examples, including production websites, getting credentials in Chrome. I asked you for a runnable repro case in the Chromium bug and you haven't provided. I was going to wait until you did so but at this point you're just spreading false information.

**Comment by mislav** [comment]
@tjwudi I just tried in Chrome 43.0.2357.65. Both `same-origin` and `include` values for `credentials:` key enable sending the cookie value. I'm sorry, but I can't reproduce what you're describing. And in your Chromium bug report, you tried to demonstrate the bug by including sample code, but then you said that the `fetch()` in the code isn't native fetch, but your own wrapper that edits the option. You'll have to provide complete code to demonstrate this issue.
