### ISSUE TITLE
Change Headers forEach parameter order to match mozilla/chrome.

### ISSUE THREAD

**Issue by WebeWizard** [github/fetch#149]
Mozilla and chrome use Value,Key parameter order.  Github fetch uses Key,Value parameter order.  This causes the developer to test for polyfill and then switch the parameter order with extra code, which could be avoided.

**Comment by dgraham** [comment]
The polyfill provides the [`forEach` method](https://github.com/github/fetch/blob/0b3e1d7c41c75359a3e0b771741ebc2a8823da38/fetch.js#L75) only because we can't polyfill the new ES6 [iterable syntax](https://fetch.spec.whatwg.org/#headers).

@annevk Is `Headers#forEach` a standard method that should be supported? It isn't in the Fetch spec, and it does not exist in Firefox, but it does exist in Chrome's implementation.

**Firefox Nightly**

```js
h = new Headers()
h.append('one', 1)
h.append('two', 2)
h.forEach(console.log.bind(console))
// => TypeError: h.forEach is not a function
```

**Chrome**

```js
h.forEach(console.log.bind(console))
// => 1 one Headers {}
// => 2 two Headers {}
```

**Comment by domenic** [comment]
It is in the Fetch spec. It is implied by http://heycam.github.io/webidl/#idl-iterable (as is entries, keys, and values).

**Comment by WebeWizard** [comment]
Thanks everyone.
