### ISSUE TITLE
improve mock ability

### ISSUE THREAD

**Issue by johann-sonntagbauer** [github/fetch#162]
I want to use the fetch api in combination with sinon mocks. Sinon mocks by now intercept XHR Requests only. To have a quick win I want to apply the polyfill always during tests to let sinon intercept and provide mock data. Please let me know if this is a good idea and i should file a PR. 

During the loading of the polyfill the global variable `allwaysApplyPolyfill` will be checked to apply the polyfill anyhow.
```javascript
if (!allwaysApplyPolyfill && self.fetch) {
    return
  }
```

When you load the polyfill with webpack you can use the Imports loader like follows to instrument the polyfill during tests.

```javascript
new webpack.ProvidePlugin({
      'fetch': 'imports?this=>global,allwaysApplyPolyfill=>true!exports?global.fetch!whatwg-fetch',
      'es6-promise': 'es6-promise'
    })
```

THX for the great polyfill.

**Comment by dgraham** [comment]
The polyfill [uses XMLHttpRequest](https://github.com/github/fetch/blob/89ae0c26e2b6c2697ec8d45b1663934e613bd32d/fetch.js#L277), so if that's already being replaced with a mock object, the tests should work.

**Comment by mislav** [comment]
@johann-sonntagbauer I guess you're requesting an option to force the polyfill. We won't provide that option (#147) and for your use-case I suggest that you intercept the `window.fetch()` calls in your apps to provide mocking in tests rather than stubbing XMLHttpRequest, which may or may not be used in the background depending on the browser version.

If a library to mock `window.fetch()` responses doesn't exist yet, you might write some helpers just for your test suite, and possibly open source it as a library if it turns out well. We would be interested in seeing how it turns out. Remember that the fake `fetch()` function should return a Promise that can already be resolved with a fake Response object, or rejected with an error.

**Comment by johann-sonntagbauer** [comment]
Thx for the fast reply and additional insight. My strategy for now is to wrap the fetch calls and provide a mock implementation on that level.

Keep up the good work.

**Comment by wheresrhys** [comment]
I wrote this npm module to mock fetch https://www.npmjs.com/package/fetch-mock

**Comment by johann-sonntagbauer** [comment]
@wheresrhys Thx for the hint. Your mock implementation looks pretty solid. I will give it a try for sure.
