### ISSUE TITLE
Export fetch function

### ISSUE THREAD

**Issue by jpochyla** [github/fetch#180]
Exporting the `fetch` function through `module.exports` would allow me to use the polyfill instead of buggy browser implementations. For example, current Chrome Canary incorrectly throws on 504 response, without any sensible way of detecting the cause of error in the catch handler.

**Comment by dgraham** [comment]
Please open a bug report with the Chrome team regarding the incorrect behavior. This polyfill is not intended to mask browser bugs, only to provide the `window.fetch` global in browsers without any `fetch` implementation at all.

**Comment by jpochyla** [comment]
Can I ask what is the reasoning behind that? Hiding the implementation behind a global and making it absolutely impossible to access otherwise seems overly limiting, and not adding anything.

**Comment by runn1ng** [comment]
If I understand @jpochyla correctly, he is mostly complaining that the `fetch` cannot be accessed on browsers that already have `fetch`. There is no reason this module cannot export itself via `module.exports`.

**Comment by mislav** [comment]
@jpochyla Here is how to force the polyfill.

```html
<script>window.fetch = undefined</script>
<script src=fetch.js></script>
```

@runn1ng We don't feel that a module pattern is worth maintaining for this simple polyfill. Any faulty browser implementation of `fetch` is that browser vendor's problem and should be taken with them.

**Comment by runn1ng** [comment]
@mislav well that's a nice hack :)

**Comment by bamsebjrn** [comment]
excitera me sir but what? im jusing tor o chrome

Skickat från min iPhone

8 aug. 2018 kl. 09:19 skrev Jarek Rencz <notifications@github.com<mailto:notifications@github.com>>:


@mislav<https://github.com/mislav> thanks for a hint :)

Any faulty browser implementation of fetch is that browser vendor's problem and should be taken with them.

To a certain extent it's not always on the browser vendor's side. E.g.: In a project of mine, where I use fetchI experience a strange behaviour in Firefox <54 where using native fetch it produces POST requests without payload. I was able to reproduce it with 1/500-1000 ratio but I see it in production so it's a fact.

Enforcing polyfill allows me to make my app usable for such users (those are mostly Firefox 52 users)

And now to the point: Firefox 52 is the last one on Win XP and Win Vista. I don't have a comfort of telling my users to update their PCs' OS just because at some point Mozilla did something bad in fetch implementation and then they fixed it (to my best knowledge either silently or accidentally because I found no bug report about such behaviour in Bugzilla)

**Comment by mislav** [comment]
@jrencz We now export the `fetch` function (and other classes) from this library: https://github.com/github/fetch/blob/048626722124b45ed7bc58ec841822610f08798b/fetch.js#L441

This will be available in the next release.

**Comment by bamsebjrn** [comment]
Give me my 4 bitcoins and I gladlyt pay ypour Company back the thing I took at the midlle of the night from a job i got from absolutly no one—can you pls call me because one of youre admins hacked ,y coinwallet last night and stole 4 bit coins wich we have proof of..I dont care what you do to earn Money…but steeling 600000k is not ok and then accusing me of stealing


Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows 10

________________________________
Från: Mislav Marohnić <notifications@github.com>
Skickat: Wednesday, August 8, 2018 12:54:30 PM
Till: github/fetch
Kopia: call me lazlo; Comment
Ämne: Re: [github/fetch] Export fetch function (#180)


@jrencz<https://github.com/jrencz> We now export the fetch function (and other classes) from this library: https://github.com/github/fetch/blob/048626722124b45ed7bc58ec841822610f08798b/fetch.js#L441

This will be available in the next release.

**Comment by bamsebjrn** [comment]
Just give me the proper bankdetails and ill happilly pay back the sum i misstook yesterday as my first tiime working mistakes are sure to hapen.
But you are not entitled to the lottory winning of 4 bitcoins.

i will drop this as sone as my four bitcoins are returned to me, ok?
Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows 10

________________________________
Från: Mislav Marohnić <notifications@github.com>
Skickat: Wednesday, August 8, 2018 12:54:30 PM
Till: github/fetch
Kopia: call me lazlo; Comment
Ämne: Re: [github/fetch] Export fetch function (#180)


@jrencz<https://github.com/jrencz> We now export the fetch function (and other classes) from this library: https://github.com/github/fetch/blob/048626722124b45ed7bc58ec841822610f08798b/fetch.js#L441

This will be available in the next release.
