### ISSUE TITLE
Errors are being swallowed up

### ISSUE THREAD

**Issue by volkanunsal** [github/fetch#194]
I have noticed that the errors originating from somewhere in my app are getting lost in promises after I started fetching from a url with this library. It's the only library I use that uses promises. I have read that the native Promise API automatically rejects unresolved promises. Could this be the case?

**Comment by mislav** [comment]
It's not easy for exceptions in your app to suddenly start getting swallowed when using this library, or Promises in general. If exceptions are getting swallowed in your app, that might be a fault of an overly zealous error handler that you might have installed.

Here's a quick rundown how Promises error handlers work, with `fetch()` as an example:

```js
fetch('/example').then(done, err1).catch(err2)
```

The `err1` handler is optional and will receive exceptions that come from failed HTTP requests, such as network errors. HTTP statuses in the range 200–599 are all considered "success" and handled by the `done` handler. However, if there's an exception inside the `done` handler (i.e. in your app's code), the `err1` handler won't get invoked.

The `err2` handler installed with `catch()` is also optional and will handle both exceptions from failed HTTP requests and those originating from `done` handler. Thus, it handles a wider range of scenarios than `err1`.

So, in your app you might have defined a handler such as `.catch(err2)` in the example above in hopes to ignore and discard HTTP network failures, but in the process you're also accidentally silencing any exceptions that come from the `done` handler.

Otherwise, if there is an exception that happens within any of the promise handlers and is uncaught, it will eventually get reported in the browser's error console. For instance, Chrome prefixes such error messages with "Uncaught (in promise)".

It's simple: if you haven't caught the exception anywhere in the promise yourself, it will get handled by the usual top-level error handling mechanism of the browser.

* * *

Note: in certain async scenarios, such as handling some events, throwing an exception manually in my experience won't propagate to the page's global `onerror` handler and won't show up in the browser's error console. I have no explanation for this. What I do in such cases is throw the error manually in a `setTimeout` block:

```js
var err = new Error("my message")
setTimeout(function(){
  throw err
}, 0)
```

**Comment by volkanunsal** [comment]
> The err2 handler installed with catch() is also optional and will handle both exceptions from failed HTTP requests and those originating from done handler. Thus, it handles a wider range of scenarios than err1.

Thank you for this thorough explanation, @mislav . This is exactly the problem I had. I took my code straight out of README, where the catch clause is used without any warnings about this behavior. Would you perhaps add this explanation into the README or a wiki page? I have a feeling that I may not be the last one to have this bug.

**Comment by dgraham** [comment]
HTML5 Rocks has a good tutorial on [Promise error handling](http://www.html5rocks.com/en/tutorials/es6/promises/).

**Comment by mislav** [comment]
> I took my code straight out of README, where the catch clause is used without any warnings about this behavior.

I feel that our `.catch()` examples in the README are not an antipattern because they at least do log any exception that occurs. If they simply ignored the exception, then they would be an antipattern. You should only even ignore specific exceptions by their class or message text.
