### ISSUE TITLE
fetch returns an empty object

### ISSUE THREAD

**Issue by ArmendGashi** [github/fetch#224]
I am trying to use whatwg-fetch with webpack and require, it returns an empty object.

```
const fetch = require('whatwg-fetch');
console.log(fetch); // Object {}
```

I would expect ```require('whatwg-fetch'); ``` to return the fetch function, I might be using it wrong in the first place, suggestion?

**Comment by mislav** [comment]
You haven't told us which module loader you use. Please refer to the documentation of your loader to learn how to require a file. [Here are Webpack instructions](http://mts.io/2015/04/08/webpack-shims-polyfills/).

We can't help you with other module loaders, though. See #46. It might be easier to just require the file normally, or concatenate your JS files together in a bundle.

**Comment by ArmendGashi** [comment]
i'm using imports-loader and exports-loader , and its the same configuration as it is in instructions

```
plugins: [
  new webpack.ProvidePlugin({
    'fetch': 'imports?this=>global!exports?global.fetch!whatwg-fetch'
  })
]
```

**Comment by mislav** [comment]
Sorry, I don't know what's going on. I've never used Webpack. Maybe refer to their documentation?

/cc @fourlastor https://github.com/github/fetch/pull/110/files

**Comment by fourlastor** [comment]
He's doing the right thing but I can't say from my phone if that's the correct setting. You might try to do it as per my pull request and it should work.

@mislav webpack uses a personalized way to import stuff, so you'll have to change things a bit if the library you're trying to import isn't commonjs compilant. Import and export module act so that you can have certain variables that the included script expects set up beforehand. To a clearer explanation looks at the doc on webpack, it's clearer :p

**Comment by ArmendGashi** [comment]
@mislav everything seems to be working thanks, also @fourlastor the loader name is incorrect , fixed and pushed

**Comment by mislav** [comment]
@ArmendGashi So now it works? What needed changing?

**Comment by mislav** [comment]
Oh I see: https://github.com/github/fetch/pull/110/files#r42432669

Well, we don't have those outdated instructions in the README anymore, and the blog post that we link to suggests installing the proper names: `imports-loader/exports-loader`.
