### ISSUE TITLE
Support for multiple cookies

### ISSUE THREAD

**Issue by leandroal** [github/fetch#236]
Hi folks...

In a simple test I was running, the webserver sent the following response header:

```
Date: Thu, 26 Nov 2015 23:07:42 GMT
Server: Apache/2.4.16 (Unix)
Set-Cookie: CookieTesteName1=CookieTesteValue1; expires=Fri, 27-Nov-2015 00:07:42 GMT; Max-Age=3600; path=/folder; domain=.domain.com; secure
Set-Cookie: CookieTesteName2=CookieTesteValue2; expires=Fri, 27-Nov-2015 00:07:42 GMT; Max-Age=3600; path=/folder; domain=.domain.com; secure
CustomHeaderName: CustomHeaderValue
Content-Length: 2397
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html
```

Please, note that there is two "Set-Cookie", but response.headers["Set-Cookie"] using cordova-plugin-fetch only returns a string containing the last "Set-Cookie" value. Is this the expected result?

**Comment by dgraham** [comment]
See #138 and #163 for a discussion of forbidden headers and cookies.

In the general case, with the exception of forbidden headers, the expected behavior is to [append all values](https://github.com/github/fetch/blob/133bd7321019cd825989ad8dcab8c96725e0b612/fetch.js#L260-L270) for each header to the headers list. For example, if the response includes these headers:

```
Server: Apache/2.4.16 (Unix)
Server: nginx
```

then accessing the `Server` header returns both values:

```js
values = response.headers.getAll('Server')
// => ['Apache/2.4.16 (Unix)', 'nginx']
```
