### ISSUE TITLE
DELETE method unexpected end of input

### ISSUE THREAD

**Issue by sethen** [github/fetch#242]
Trying to do a delete on a REST API like this:

```javascript
return fetch('https://api.insightpool.com/v1/sessions', {
    headers: {
        'Access-Token': 'token'
    },
    method: 'delete'
}).then((data) => {
    data.json().then(json => {
        return json;
    });
});
````

This yields an error like `Uncaught (in promise) SyntaxError: Unexpected end of input`.  I am not exactly sure why this is being thrown.  I checked my code with the examples in some other issues and against the documentation.  If I take off the `then` I no longer get the error.

Is there something I am doing wrong here?

**Comment by dgraham** [comment]
It's possible the server is rejecting the CORS request and returning HTML rather than the expected JSON response. You can try `data.text().then(text => console.log(text))` to inspect the response, or use the browser's Network inspector to view the full request and response headers.

[CORS settings](https://github.com/github/fetch#sending-cookies) are discussed in the readme.

**Comment by sethen** [comment]
Thanks!
