### ISSUE TITLE
Synchronous flag?

### ISSUE THREAD

**Issue by danostrowski** [github/fetch#248]
The fetch standard mentions a synchronous flag, here: https://fetch.spec.whatwg.org/#synchronous-flag

As far as I can tell, the current code has hard coded to call xhr asynchronously: https://github.com/github/fetch/blob/master/fetch.js#L363

Is there opposition to adding this? Has it been discussed? Thanks!

**Comment by dgraham** [comment]
A `synchronous` attribute isn't listed in the [`Request` definition](https://fetch.spec.whatwg.org/#request). It looks like an internal implementation detail.

I would be surprised to see synchronous requests added to `fetch` because they are [deprecated for `XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest?redirectlocale=en-US&redirectslug=DOM%2FXMLHttpRequest#open()).

**Comment by GitShaffi** [comment]
@danostrowski @dgraham So, is there a way to make Fetch synchronous now??

**Comment by mislav** [comment]
It seems that [synchronous option was added to the spec](https://fetch.spec.whatwg.org/#synchronous-flag). If anyone is interested in submitting a PR that implements this behavior, we would review it and consider pullig it, but please note that if this flag was used, it could trigger browser deprecation warnings.

**Comment by ORESoftware** [comment]
Ok so how can we make a synchronous AJAX request with the fetch API?

**Comment by dgraham** [comment]
@mislav The synchronous option isn't exposed as API in the [Request class](https://fetch.spec.whatwg.org/#request-class). It looks like more of an implementation detail for browsers.

@ORESoftware There is no way to perform a synchronous fetch request. You'll need to use XMLHttpRequest.
