### ISSUE TITLE
Why use getOwnPropertyNames?

### ISSUE THREAD

**Issue by othree** [github/fetch#281]
Sorry.
This is not a bug, but I think there is no other better place for this question.

I want to ask why use `getOwnPropertyNames` in [header class](https://github.com/github/fetch/blob/master/fetch.js#L34).
In my opinion, a `for...in` loop can also deal with the scenario.
Is there any concern or edge case I didn't notice.

Thanks

**Comment by mislav** [comment]
This is most likely do deal with the scenario where a plain object (`{}`) of key-value pairs has been passed, but Object.prototype might have extended by other scripts on the page.

Extending Object.prototype isn't common practice nowadays, but it still makes sense to guard against it since it's relatively straightforward.

Does this answer your question?

**Comment by dgraham** [comment]
```js
Object.prototype.foo = 42
var object = {a: 1, b: 2, c: 3}

Object.getOwnPropertyNames(object)
// => ['a', 'b', 'c']

for (var property in object) console.log(property)
// => 'a', 'b', 'c', 'foo'
```

**Comment by othree** [comment]
Thank you @mislav and @dgraham. Solves my question :smile:
