### ISSUE TITLE
Is it possible to run something in every request start/end?

### ISSUE THREAD

**Issue by vapits** [github/fetch#300]
Hi there,

this is not a bug or real issue but I'm wondering if it's possible to setup fetch someway to execute something before and after each request, but globally?

Like $http interceptors in AngularJs or like $.ajaxStart/Stop in jQuery.

If not, that would be great addition IMO.

Take care!

**Comment by mislav** [comment]
Hi. This is a good question and something that would undoubtedly be useful, but we're not at liberty of adding new features because this polyfill needs to conform to the whatwg-fetch spec.

However, you can add this functionality yourself without the assistance of either this polyfill or the native fetch specification: simply override `window.fetch()` function.

```js
// First, ensure that this polyfill has loaded. Then:
var originalFetch = window.fetch

function onFetchStart() {
  console.log("fetch was called with", arguments)
}

function onFetchStop() {
  console.log("fetch has loaded response", arguments)
}

window.fetch = function() {
  onFetchStart.apply(null, arguments)
  return originalFetch.apply(this, arguments).then(function(response) {
    onFetchStop.call(null, response)
    return response
  })
}
```

This is a somewhat naive implementation intended just for you to get the idea. The rest is left as an exercise to the reader. Good luck! 😉
