### ISSUE TITLE
iOS 9.3 can't handle this polyfill

### ISSUE THREAD

**Issue by Nickvda** [github/fetch#302]
Greetings,

I have grabbed one of the examples as a way of testing this out. Sadly, it stops the webapplication from working on iOS. Have tried debugging it, but sadly Ghostlab is working against me on that front!

I did manage to find out that the app dies either on or after the fetch command, as no Javascript is executed after it. This issue happens on iOS 9.2 as well. This is the example code:

        fetch(WorkingURLConstant, {
            credentials: 'include'
        }).then(function (response) {
                if (response.status >= 400) {
                    throw new Error("Bad response");
                }

                return response.json();
            }).then(function (parsedData) {
                // processing of the data (with these lines gone, same happens*)
            });

**Comment by mislav** [comment]
I just tried to run our entire test suite on iOS 9.3 and it passes. This leads me to believe that the error is in your application, rather than in our polyfill.

JavaScript libraries typically don't have the power to halt all JavaScript execution in the browser. So your description of the problem (that the app dies and no JavaScript is executed after that) is a little hard to believe. To take this as a proper bug report, you'll have to give us a little more information about your environment, the nature of the error you're seeing, and hopefully steps to reproduce.

If you, on the other hand, conclude that the error is in your setup instead, please update this anyway. Good luck!

**Comment by Nickvda** [comment]
Turns out it's probably a faulty authentication cookie that's not being set or sent. I am building a React application, which means _everything_ is built through Javascript, so if an error occurs.. It just blanks out (like I'm seeing now). Sadly, the Ghostlab debugging features are not working, so I'll have to find a way to get some information on the screen.

Thanks regardless for the poke- it's what spurred the idea about authentication. Cheers!

**Comment by mislav** [comment]
Similar React native app cookie problem: https://github.com/github/fetch/issues/284#issuecomment-189776131

**Comment by Nickvda** [comment]
Thanks for the pointer, mislav! But after some debugging it seems to be this issue; 'ReferenceError: Can't find variable: fetch'. Have been looking for solutions, but none as of now!

**Comment by mislav** [comment]
Sorry, @Nickvda, we don't know how you load project files in your application or how to debug it. You'll have to do it yourself. This is the way I would load the fetch polyfill if all else fails:

```html
<script src="path/to/fetch.js"></script>
```
