### ISSUE TITLE
Why drop support for IE9?

### ISSUE THREAD

**Issue by TheSavior** [github/fetch#326]
Why did support for IE9 get dropped in this polyfill? I'm sure there are technical reasons, but it means we have to stay on an old version to be able to keep using this in production.

**Comment by mislav** [comment]
More information here: https://github.com/github/fetch/issues/214#issuecomment-145516741

In short, workarounds for IE9 bugs were limiting the use of this polyfill. So instead of further maintaining those workarounds, we decided to drop them. We are not interested in maintaining a IE9-compatible library because we don't support IE9 on GitHub.com anymore and therefore don't test with it.

**Comment by dlong500** [comment]
Somewhat unfortunate especially since Vista users can't get IE10.  Of course there are other browsers, but still.  It would have been nice to maintain IE9 support at least until the end of extended support for Vista (4/11/2017).  Do you see any problems (security or otherwise) with continuing to use the older version for the next year?

**Comment by mislav** [comment]
You should be fine by using v0.11.0 indefinitely. It wouldn't be hard for us to release another v0.11.x series with just bugfixes (currently there's only one re: timeout handling) and no v1.0 features, which are non-essential anyway.

**Comment by evolutionxbox** [comment]
@dlong500 I do see your point about the extended support for Vista, but wasn't it Microsoft themselves who recently dropped support for all [IE browsers before IE11 no matter the platform](https://support.microsoft.com/en-gb/lifecycle?p1=15672)?

**Comment by dlong500** [comment]
@evolutionxbox Microsoft's current policy is to support only the latest version of IE for an available supported OS.  Since you can't get IE10 on Vista then IE9 is the latest version of IE for Vista and is thus supported until the end of the extended support period.

Believe me, I don't care for IE9 at all, but I can't necessarily just tell any potential users of my projects to upgrade their OS or switch to another browser.  With Chrome not supporting Vista at this point the options start to get pretty limited.  Firefox is the only browser that continues to receive updates on older systems at this point.  Given Microsoft's new zeal for change it would appear the days of so many OS versions coexisting may be near an end.

**Comment by mislav** [comment]
Just published https://github.com/github/fetch/releases/tag/v0.11.1 with the same bugfixes that went into v1.0. Feel free to use that for a long time if you need support IE9.

**Comment by klimashkin** [comment]
@mislav But now `npm outdated` and other tools say that `0.11.1` is the latest version, instead of `1.0.0` :)

**Comment by klimashkin** [comment]
Moreover, now if user just types `npm i whatwg-fetch` it will install 0.11.1 as latest version

**Comment by dgraham** [comment]
We could publish a 1.0.1 release to work around this npm semantic versioning bug.

**Comment by mislav** [comment]
> now if user just types `npm i whatwg-fetch` it will install 0.11.1 as latest version

What. That is ridiculous. If npm behaves this way, we can't publish any bugfix releases from any past stable branches ever. How do other npm projects do this?

Don't tell me no npm packages ever release bugfixes from past stable release branches. 😲

**Comment by mislav** [comment]
Okay, with the help of @badboy on Twitter I've come to the realization that this is expected npm behavior because every `npm publish` by default overwrites a “distribution tag" called `latest`. Fixed with:

```
npm dist-tag add whatwg-fetch@1.0.0 latest
```

I guess when we publish past bugfix releases we need to specify the distribution tag explicitly with `--tag=foo`. I'm not sure what we should call the custom distribution tag, though.

**Comment by ljharb** [comment]
@mislav you can call it anything you like, and then use `npm dist-tag rm` to remove it. it just defaults to "latest", so you'll want to always provide it when not publishing the latest.
