### ISSUE TITLE
Redirect and CORS

### ISSUE THREAD

**Issue by blanchma** [github/fetch#397]
I'm using fetch to go through an OAuth2 process. In some point, I have a 302 (an opaqueredirect) and I can make it work: 

redirect = 'follow'
Fetch API cannot load http://google.com/?code=c416ff68bafc136d6e47a62a62176d369e919e624d4a9226. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3001' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

And redirect= 'manual' given is opaque I can't see the final destination.

**Comment by caseybaggz** [comment]
I have a similar problem. I'm sending a `POST` to an oauth server, which sends back a 200, but fetch is only recognizing the status as `opaque` with ok being `false`.

fetch:
```
fetch(`${ this.testingURL }/oauth/token?${ params }`, {
      credentials: 'include',
      mode: 'no-cors',
      method: 'POST'
    })
    .then(FetchHelper.status) // fails here
    .then(FetchHelper.parseJSON)
    .then((json) => {
      console.log('it worked');

      callback({
        authenticated: true,
        token: json.access_token
      });
    })
    .catch((e) => {
      callback({
        authenticated: false,
        token: null
      });
    });
```

FetchHelper:
```
export default class FetchHelper {

  static status(response) {
    // response.status === 'opaque' but in Network tab it's 200
    if (response.status >= 200 && response.status < 300) {
      return response;
    } else {
      throw new Error(response.statusText);
    }
  }


  static parseJSON(response) {
    return response.json();
  }

}
```

**Comment by mislav** [comment]
Hi, sorry, we can't answer support questions about cross-domain usage. CORS is complicated and it's very easy to get it wrong. Since it's mostly handled by the browser and the native fetch/XMLHttpRequest implemenation, there's very little about this we can do from our fetch polyfill, and what people perceive as fetch polyfill bug is usually an error in their CORS setup or expectations. I hope you will be able to debug your issue by yourself!
