### ISSUE TITLE
import to typescript

### ISSUE THREAD

**Issue by Shavindra** [github/fetch#398]
Hi 

I am trying to import this via typescript
`import fetch from 'whatwg-fetch'`

However I am getting `'cannot find module whatwg-fetch`. I installed typings.

Which now give errors in `whatwg-fetch/index.d.ts` because it can't find name `Promise`, `IterableIterator` etc?

how can I resolve this? I am using VS 2015.

**Comment by mislav** [comment]
I have no experience with TypeScript, therefore I can't be helpful here. However, this library needs `Promise` in order to work. So, when you import `whatwg-fetch`, you also have to make sure that you've imported some Promise polyfill as well. I don't know what is IterableIterator or why that's needed.

Again, I have no idea how to use this library in TypeScript, and since we don't use TypeScript ourselves, we can't assist you very much further. Sorry about that! I hope you will figure it out.
