### ISSUE TITLE
Fetching unauthorized resource causes TypeMismatchError on Edge

### ISSUE THREAD

**Issue by BorelTung** [github/fetch#409]
Since it's a [bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8653298/) on some version of Microsoft Edge, we cannot ignore it. Should we fix it in this polyfill?

**Comment by BorelTung** [comment]
I think the [support level](https://github.com/github/fetch#browser-support) it not enough. It means who using this polyfill should fix all those issues in their projects.
Or, it there any solutions for issues like that?

**Comment by mislav** [comment]
What do you propose we do in the polyfill? We are not in the business of fixing broken browser implementations, unless it's a really easy workaround.

**Comment by dgraham** [comment]
Thanks for letting us know about this bug in Edge's native fetch implementation. It's marked as fixed, so the next version update of Edge should work properly.

Because an error is returned, rather than a  `Response`, we can't workaround the problem because the response body and headers are unavailable.

**Comment by BorelTung** [comment]
Thank you for your replies. @mislav @dgraham
