### ISSUE TITLE
es6-promise is not a safe polyfill to recommend in your readme

### ISSUE THREAD

**Issue by nilliams** [github/fetch#415]
See exact same issue raised here: https://github.com/matthew-andrews/isomorphic-fetch/issues/111

Make sure you don't skip the arguably worse examples here: https://github.com/matthew-andrews/isomorphic-fetch/issues/111#issuecomment-255443016

**Comment by dgraham** [comment]
We recommend that polyfill because we've been using it successfully in production for a few years. Keep in mind that the Promise polyfill is active only in IE. All other browsers provide a native implementation that disables the polyfill code.

That specific Promise library is not a requirement to use the fetch polyfill. Any other Promise implementation is fine. But we can only recommend libraries we have production experience with.

**Comment by nilliams** [comment]
Understood and to be clear, the last time I looked that up that was not the case, I believe the polyfill used to be applied in all browsers, even if they had a native implementation, otherwise I would have only hit this error in CI, which wasn't how I remember it.

However I just tried to replicate the demonstrated errors with exact usage example of how you'd use it with fetch and could not, so I think you're correct there.

Still, IE usage is not insignificant for most sites, so I still think this is going to cause people problems, and it's a shame to see it closed so quickly.

**Comment by mislav** [comment]
> We recommend that polyfill because we've been using it successfully in production for a few years.

It's also worth noting that we've been using es-promise 1.0.0 all this time because of that project's [careless release process around 2.0](https://github.com/stefanpenner/es6-promise/issues/75).
