### ISSUE TITLE
Safari on iOS doesn't send ssl certificate on fetch request

### ISSUE THREAD

**Issue by jonathanwilke** [github/fetch#441]
Hi guys,

I'm working on a react web app and I'm using fetch to get the data from our servers and we use self-signed SSL certificates. The problem is that in safari on iOS this certificate isn't sent with the fetch request. Does anyone have this problem too and knows a workaround?

**Comment by mislav** [comment]
When this polyfill kicks in, which is true for Safari, fetch is implemented simply with XMLHttpRequest. If Safari on iOS chooses not to send the client certificate, there's nothing we can do about it from the polyfill, since we can't manipulate SSL certificates using the XMLHttpRequest API. I'm sorry, but it looks like you might need to explore a different approach to strengthen security of your app.
