### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by dorajam** [github/fetch#450]
I use fetch to send data to my back end on [this](https://portfolio.dorajambor.com:8000/) web application.

It runs fine on my localhost without any problems, yet once I start serving it, it's giving me this strange error pointing to fetch as the responsible party.

Not sure if this is indeed because of fetch, but if it is, does anyone know a fix for stabilising its behavior through different servers? Thanks!

PS. An additional message after the 500 error says `Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0`, again something that doesn't seem to be a problem on my local.

**Comment by mislav** [comment]
Hi, I'm sorry you're having trouble. From my experience, these types of errors are usually due to miscommunication between the server and the client, rather than in the `fetch` functionality itself. From the error message that you shared, it's clear that the JavaScript code was calling `response.json()` to attempt to parse the `application/json` response from the server, but it seems that the server responded with `text/html` instead, probably because there was a HTTP 500 error on the server and most error pages are by default in HTML instead of JSON.

You have shared with us very little detail about your setup, but even if you shared more, it would be nearly impossible for us to figure out why your server is returning HTTP 500, since we don't have access to its logs. If you viewed the server log, there would probably be a stack trace of the exception there, which would send you on a good track to debug this issue.

Also please be sure to have read [the Caveats section](https://github.com/github/fetch#caveats) to understand how `fetch` handles HTTP error codes and cookies for authentication.

Good luck!

**Comment by aeciolevy** [comment]
@dorajam this error "PS. An additional message after the 500 error says Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0, again something that doesn't seem to be a problem on my local." is from the JSON response from your server. If you are send a json response in success(Promise solve), it should be a object. If you send Promisse reject the error is already a object, so that no error.
