### ISSUE TITLE
support for fetch !!

### ISSUE THREAD

**Issue by ashwinimnnit** [github/fetch#455]
Is there any global feature in fetch which can be executed after any response arrived .

**Comment by mislav** [comment]
No, there is not a callback nor an event you can subscribe to equivalent to jQuery's global `ajaxComplete`. I personally find this to be a big ommision of the fetch spec. But, if you have such a feature idea, you should search for existing discussions or open a new one [in the official repository](https://github.com/whatwg/fetch/issues?page=2&q=is%3Aissue+event&utf8=%E2%9C%93), rather than here. Thanks!
