### ISSUE TITLE
Receiving custom error messages

### ISSUE THREAD

**Issue by peramsathyam** [github/fetch#458]
Couldn't receive custom error messages that is responded by express server

http://expressjs.com/en/api.html#res.send
http://expressjs.com/en/api.html#res.json

Still I get the default `statusText` in response 

For example,
`res.status(400).send({ message: 'Password reset token is invalid or has expired' });`
I get `statusText=Bad request`  and I don't receive `message`

**Comment by mislav** [comment]
Your question is about Express and therefore is more suitable for some Express.js support group rather than here.

You are sending the `{"message": "..."}` payload as response body and expecting it to be available as `statusText`. It doesn't work that way, since `statusText` is always separate from response body.

You want this (tested with Express 3.1):

```js
res.writeHead(400, 'Password reset token is invalid or has expired')
res.end()
```
