### ISSUE TITLE
'Can't find variable : fetch' on Safari 10.0.1

### ISSUE THREAD

**Issue by li-huo** [github/fetch#461]
hi there, my understanding is that this polyfill fetch should support Safari 6+. However even if I import 'whatwg-fetch' before using fetch keyword, i still get this error message.

Just want to confirm if 'whatwg-fetch' works with the safari 10.0.1?

**Comment by mislav** [comment]
Yes, the polyfill will apply to any browser that doesn't implement `widow.fetch` itself, and Safari 10.0.1 is among them. Therefore, if you've loaded whatwg-fetch properly, the `window.fetch()` function is guaranteed to be defined. 

It sounds like you didn't import whatwg-fetch in a correct way, but we can't help with that, because everyone seems to import libraries in their projects a little differently.
