### ISSUE TITLE
QQ browser bug

### ISSUE THREAD

**Issue by wupengFEX** [github/fetch#466]
I found fetch library has bug in huawei p8 qq browser, request can't send successfully.could you see and fix it?

**Comment by wupengFEX** [comment]
@mislav fetch failed in oppo, vivo, huawei mate8, huanwei p8, xiaomi 5 qq browser, Are they listed in the repair plan?

**Comment by mislav** [comment]
We only support these browsers in this polyfill: https://github.com/github/fetch#browser-support (or, at least, the older versions of these browsers before they added their own native implementation of `fetch`). We can't guarantee compatibility in every other browser. Very old or obscure mobile browsers might not work since the implementation assumes that the JS environment at least has support for XMLHttpRequest 2.

If you found a bug in a browser that is important to you and you think a workaround would be simple, we would welcome a Pull Request with a patch and an explanation! But for now, I'm going to close this, because we don't aim for compatibility with the browsers that you've listed.

**Comment by jeanys** [comment]
@wupengFEX  Hi, 我还在项目选型中，移动端fetch兼容性有解决方案了吗？我的搜索结果让我感觉目前在移动端生产环境中还不能用。
