### ISSUE TITLE
IE11 XHR calls aborted

### ISSUE THREAD

**Issue by enrico-padovani** [github/fetch#471]
Hi folks,

I'm having a strange problem with internet explorer 11. My setup is a SPA that interacts within an ASP.NET Web API server using CORS and NTLM authentication.

The site It's working fine in every part, but when the user hold on one page (for example 5 mins => go bathroom) then every call is rejected (Aborted). If any GET operation is made, then the calls with other verbs are working fine. Again, this is not happening with GET verb but I've notice it when using PUT and POST.

Does anyone had a similar problem?

**Comment by mislav** [comment]
I'm sorry that you're having a problem. I don't think we can help through this issue tracker. We [already indicated in the README](https://github.com/github/fetch#read-this-first) that CORS is notoriously hard to set up and debug, especially for non-GET requests. It's also something that we can't affect through this polyfill, since all the browser mechanisms for handling CORS are internal, and even if there were a browser bug with it, we wouldn't be able to change the polyfill to work around it.

I recommend that you set up a debugging HTTP proxy (my tool of choice is Charles proxy) to inspect communication that IE is doing with the server, and then pay attention to CORS headers.
