### ISSUE TITLE
Error with FormData as Body

### ISSUE THREAD

**Issue by Tempuser000** [github/fetch#476]
Using fetch.js, the following will throw out error 'could not read FormData body as text':

```js
var formData = new FormData();
formData.append('username', 'Chris');
var request = new Request('http://localhost:9001/testpage', {method: 'POST', body: formData});
var fData = request.formData();  // <------- error is thrown out.
```

The reason being that formData() always just decodes whatever text() returns but text() throws error if the body is actually of FormData. 

The following code: 

```js
    if (support.formData) {
      this.formData = function() {
        return this.text().then(decode)
      }
    }
```

should be:

```js
    if (support.formData) {
      this.formData = function() {
        if (this._bodyFormData) {
          return Promise.resolve(this._bodyFormData);
        } else {
          return this.text().then(decode)
        }
      }
    }
```

**Comment by mislav** [comment]
You are welcome to send a PR to fix this in our polyfill, but as I've pointed out in https://github.com/github/fetch/issues/460#issuecomment-271606463, the cross-browser support for `formData()` isn't great, and you will have trouble running your code on Chrome, which doesn't implement `formData()` at all. That's why we're not overly motivated to improve this in the polyfill, because we're not sure how it should act in various edge cases.

I'm going to close this one out as something that was discussed before, but as I've said, a PR with your change (and accompanying test) is welcome!
