### ISSUE TITLE
Fetch traversal to return to the JSON problem, the length of the interception will exceed

### ISSUE THREAD

**Issue by lihua123569** [github/fetch#497]
If I have the background of return data as follows: {"total": 24, 3: "current", "records", "age" [{: 2, ID: 842991840004247552, name: 222, testType: 3}
JSON string, the background of the ID is long type, the value of 842991840004247552 more than the length of the, then take out the data will be fetch into the 842991840004247500, the last two were intercepted into a 00. JS Ajax will not become so

**Comment by Tzook** [comment]
The number is larger than the [Max Safe Integer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) (9007199254740991).
Any number above that is [not safe to use](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger). 
Prefer to represent the id as a string instead of an integer instead.

**Comment by fewiki** [comment]
custom fetch.js will solve bigint problem
`
const JSONbig = require('json-bigint-string');

// rewrite json
this.json = function() {
      return this.text().then(JSONbig.parse)
    }

`
