### ISSUE TITLE
Provide a general function to check if fetch is performing a request

### ISSUE THREAD

**Issue by djlebersilvestre** [github/fetch#516]
I'm trying to find a function similar to `$.active` from Jquery. The idea is to be able to evaluate if a request is being processed using javascript.

Maybe fetch already provides something like this, but I couldn't find.

The main problem I'm trying to solve right now is how to `wait_for_ajax` inside a Capybara test that uses `fetch` in the UI. Example: https://robots.thoughtbot.com/automatically-wait-for-ajax-with-capybara

Any suggestions?

**Comment by adz5a** [comment]
Hello, maybe the easiest way is to try and build such a function yourself, along the lines of something like : 
```
(function (window, fetch) {

    window.fetchActive = 0;
    const inc = () => window.fetchActive++;
    const dec = () => window.fetchActive--;

    return function () {

        const req = fetch.apply(undefined, [].slice.apply(arguments, 0));

        inc();
        req.then(dec, dec);


        return req;

    };

} (window, fetch));
```

And in your helpers file you can `page.evaluate_script('window.fetchActive').zero?` to test if a request is being processed.
Beware though there is still a race condition as fetchActive can be at zero but handlers are still waiting to be processed. Listening to network is not the same as listening the the UI being refreshed, so in order to cover all your bases you can implement the same mechanism around the "render function" which gets called each time your UI is refreshed and synchronously refreshes it.

**Comment by djlebersilvestre** [comment]
Great!! Thanks :)

**Comment by kpheasey** [comment]
@adz5a Thank you!  That fixes all of my testing issues!
