### ISSUE TITLE
In IE11 resolve is not always executed

### ISSUE THREAD

**Issue by petronellius** [github/fetch#533]
Our app is making scheduled request every N seconds. After some time IE11 stops doing requests.
I try to search web and it looks like there is a bug in IE11. It does not handle XHR callbacks properly.
See similar issue on [bluebird repository](https://github.com/petkaantonov/bluebird/issues/1161).
So I try workaround - wrap resolve to setTimeout and it works.

**Comment by mislav** [comment]
Thanks for letting us know. Unfortunately, I don't think there is anything we can do here to fix IE behavior, sans wrapping every XHR call in an arbitrary `setTimeout`. We won't do that, because if we choose a value for the timeout e.g. 10 seconds, then we prevent everyone from making requests that may take longer than 10 seconds.

The workaround which you can do in your project is wrapping all your `fetch` calls in a [Promise-based timeout helper as suggested here](https://github.com/github/fetch/issues/175#issuecomment-125779262).

**Comment by CrOrc** [comment]
Please reopen this issue.

This issue is not about making XHR call in setTimeout but about resolving Promise with results from **completed** XHR.

In IE 11 calling resolve within XHR onload handler may hang indefinitely if there's no active DOM operations. But calling resolve within setTimeout works fine.

**Comment by mislav** [comment]
Ah, I realize now what the OP was proposing above. Thanks for providing more information.

**Comment by ADagen** [comment]
Hey guys, let's move on.
