### ISSUE TITLE
how to get XMLHttpRequest.upload in fetch?

### ISSUE THREAD

**Issue by zzzgit** [github/fetch#538]
i am using fetch to implement a uploading functionality
the functionality have been completed
now i need to show the uploading progress
so, how to get XMLHttpRequest.upload object in fetch?

**Comment by mislav** [comment]
`fetch` specification doesn't contain functionality that allows implementing progress indicators; therefore, this library doesn't implement such functionality either. See https://github.com/github/fetch/issues/379#issuecomment-239635017

You might want to use XMLHttpRequest directly in order to implement this.
