### ISSUE TITLE
Never sends cookie header to the server

### ISSUE THREAD

**Issue by narayananramu** [github/fetch#554]
Apollo client doesn't send session cookie to Apollo server as a result I am getting empty session object on Apollo Server.

I have 3 Docker containers that run

1. Apollo Koa Server (kcors is enabled) at api.a.cloud
2. Koa (where I use Apollo Client with React) at qwerty.a.cloud
3. Nginx (for reverse proxy) at a.cloud

Apollo Koa Server Session Configuration & Koa. Also both (Apollo Server and Client) share same cookie and both work as excepted when normal browser request is sent.

```
sessionConfiguration : {
        key: '_a',
        maxAge: 86400000,
        overwrite: true,
        httpOnly: true,
        signed: true,
        domain: '.a.cloud',
        store: redisStore({
            host: "192.168.0.100",
            port: 32769
        })
}
```

Apollo Client React Snippet

```
const networkInterface = createNetworkInterface({
    uri: 'http://api.a.cloud/user',
    opts: {
        credentials: 'same-origin' //fetch_options
    },
});

const client = new ApolloClient({
    networkInterface: networkInterface
});

```

I even tried

```
const networkInterface = createNetworkInterface({
    uri: 'http://api.a.cloud/user',
    opts: {
        credentials: 'include' //fetch_options
    },
});

const client = new ApolloClient({
    networkInterface: networkInterface
});

```

Thanks in advance 👍

**Comment by mislav** [comment]
Unfortunately, I have no experience with Apollo, nor with the rest of your stack for that matter. The `credentials: 'same-origin'` setting looks good if it's indeed being forwarded to `fetch()` options, and should enable sending and receiving of same-domain cookies, but I have no idea how `createNetworkInterface` actually works internally.

This option would work for you if you used `fetch()` directly, but because you aren't (and you are most likely using the browser's native implementation of `fetch` instead of this polyfill), this issue tracker isn't the appropriate place to ask support questions. It would be better to ask on Stack Overflow or perhaps some Apollo communities such as mailing list or message boards. Good luck!
