### ISSUE TITLE
qt support

### ISSUE THREAD

**Issue by NikolaBorislavovHristov** [github/fetch#560]
Add support for qml.
`onload` is not supported in qt, `onreadystatechange` must be used instead.

**Comment by mislav** [comment]
Our polyfill depends on XMLHttpRequest Level 2 interface, which dictates that `onload` should be supported. Browsers that don't support XHR 2 are browsers that are unsupported by this polyfill, since features such as CORS, sending/receiving Blobs, or sending FormData wouldn't work anyway.

If you need to support these very old browsers, I suggest that you use XHR interface directly.
