### ISSUE TITLE
On an XMLHttpRequest error, expose error message 

### ISSUE THREAD

**Issue by aarondail** [github/fetch#565]
I am trying to get a more useful error message out of fetch when there are network errors...

For context: I am using react native, which uses this library internally for its fetch implementation.  If I am connecting to a server whose cert is invalid, or have a typo in the server name, its nicer to expose a more descriptive error message to the user.  The XMLHttpRequest that react native provides does this, but fetch ignores it and always sends back 'Network request failed'.

I believe this is because: in the fetch constructor the onerror and ontimeout callbacks from the XMLHttpRequest object are wired up like this:

```
      xhr.onerror = function() {
        reject(new TypeError('Network request failed'))
      }

      xhr.ontimeout = function() {
        reject(new TypeError('Network request failed'))
      }
``` 

Sadly, no information about what the error was from the XMLHttpRequest object is actually exposed.

Could it be changed to something like this:

```
      xhr.onerror = function() {
        reject(new TypeError(xhr.responseText || 'Network request failed'))
      }

      xhr.ontimeout = function() {
        reject(new TypeError(xhr.responseText || 'Network request failed'))
      }
```

**Comment by mislav** [comment]
There's some value in what you're proposing, but see https://github.com/github/fetch/pull/562#issuecomment-330594122 for more thoughts on the subject.

Would `xhr.responseText` be reliable as a source of error message?

**Comment by aarondail** [comment]
Sorry for the delay in responding :)

I dont know enough to answer your question.  In the context of react native, it is.  I honestly dont know about other contexts where fetch is used (browser, and others).

**Comment by dewwwald** [comment]
Chrome implementation of error object for the fetch lib:
In the console of the browser you can read a message: `Uncaught (in promise) TypeError: Failed to fetch`, however before that is additional output. As follow in this screenshot:
<img width="1326" alt="screen shot 2018-03-26 at 17 17 41" src="https://user-images.githubusercontent.com/6582424/37933633-c9e8d4bc-3119-11e8-87dd-ef59cd7391a9.png">

Firefox implementation of error object for the fetch lib:
<img width="709" alt="screen shot 2018-03-26 at 17 55 47" src="https://user-images.githubusercontent.com/6582424/37935328-109a68ee-311f-11e8-8926-bbbb4fc33c4d.png">

Safari implementation of error object for the fetch lib:
<img width="788" alt="screen shot 2018-03-26 at 17 58 35" src="https://user-images.githubusercontent.com/6582424/37935402-5c0e5c68-311f-11e8-9e3e-71fd2c911a44.png">

My point with these screengrabs is that there are things we can observe:
- Error message is clear
- Error message is not concealed behind a generic message
- Warning regarding CORS are show to ensure full awareness of the engineer (**even if a catch is present**)

Since this is a polyfil we need to consider the XmlHttpResponse response objects limitations on all browsers when showing a message, even so I think we can do better.

#### Todo

This is just a list of items I think has to be done for this to be considered complete.

[ ] determine the prototypes of the xmlHttpResponse on all known major platforms
  [ ] IOS (React Native)
  [ ] Andriod (React Native)
  [ ] ~~~Chrome~~~ _Not relevant to the scope of this library_
  [ ] ~~~Firefox~~~ _Not relevant to the scope of this library_
  [ ] Internet explorer 9
  [ ] Internet explorer 10
  [ ] Internet explorer 11
  [ ] Edge ??
[ ] write an implementation that shows a warning for unusable responses like CORS errors
[ ] write an implementation that enriches the onerror function referenced below
[ ] write a test to check each browser if the implementation hill have the desired data points

**Comment by mislav** [comment]
@dewwwald Thanks for looking into this! I appreciate your notes.

**Comment by mislav** [comment]
Closing since there is nothing left actionable for us to do after this discussion.

If anyone has ideas how to improve these error messages, PRs welcome. But please consider all the points above.
