### ISSUE TITLE
Authorization is sent in OPTIONS of preflight request, which is probably not best practice

### ISSUE THREAD

**Issue by Kielan** [github/fetch#568]
I have an api using fetch polyfill (through webpack) on this web platform, this is a secure api server that requires an Authorization header, and should only accept an empty options object due to formality in dealing with the web browser. Thoughts on how to remedy this?

**Comment by mislav** [comment]
Unfortunately, anything dealing with OPTIONS is implemented by browser's internal mechanism. Neither this polyfill nor the user can do anything from JavaScript to edit how these handlers are handled. Please see https://github.com/github/fetch#read-this-first and general documentation on CORS and how your browser handles it.

**Comment by Kielan** [comment]
thanks for closing I couldn't find this in Github. Yes the browser sends options automatically, might be a could thing for a faq page in case others make the same erroneous assumption I did.

**Comment by mislav** [comment]
CORS is a big topic which we choose not to cover in the FAQ (except mentioning that cross-domain requests are sometimes tricky to achieve) because the best place to learn about CORS is a browser documentation site such as MDN. If we chose to cover all the different pitfalls of using CORS with `fetch`, our own README would become unwieldy and hard to maintain.
