### ISSUE TITLE
add JSON Object support

### ISSUE THREAD

**Issue by zuoRambo** [github/fetch#584]
When set the xhr.responseType = "json", the console display the follow error `unsupported BodyInit type`.
```js
var support = {
    searchParams: 'URLSearchParams' in self,
    iterable: 'Symbol' in self && 'iterator' in Symbol,
    blob: 'FileReader' in self && 'Blob' in self && (function() {
      try {
        new Blob()
        return true
      } catch(e) {
        return false
      }
    })(),
    formData: 'FormData' in self,
    arrayBuffer: 'ArrayBuffer' in self,
    // add the follow line 
    json: 'JSON' in self
  }
```

**Comment by dgraham** [comment]
A parsed JSON object isn't a valid [`BodyInit`](https://fetch.spec.whatwg.org/#body-mixin) type. We don't detect support for `window.JSON` because all browsers have that API available.

I might be missing something here, so can you provide example code that is failing with this polyfill but works in Chrome or Firefox?
