### ISSUE TITLE
IE 11 PATCH request is intermittently missing the body

### ISSUE THREAD

**Issue by theDogOfPavlov** [github/fetch#588]
IE 11 version 11.0.9600.18837
whatwg-fetch 2.0.3

When using IE, if the app sends a PATCH request with multiple operations, it is intermittently missing the body (although the header is correct and intact [including the correct content-length]).

The same request works consistently on Firefox and Chrome (using their embedded fetch client).

If the PATCH request contains only a single operation then it doesn't seem to be affected in the same way.

request working ok:
```
PATCH /v1/users/2628258159781393046 HTTP/1.1
Referer: https://127.0.0.1/
Content-Type: application/json
session: Y2I7WaNHbYgycLM1FDHXsB66RNy6A9tX
Accept: application/json
Accept-Language: en-GB
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: 127.0.0.1
Content-Length: 175
Connection: close
Cache-Control: no-cache
Cookie: Tw0OlNAKsq9Qc6g5XMfJduBEn9iKDACh=session

[
    {
        "op": "test",
        "path": "/password",
        "value": "a"
    },
    {
        "op": "replace",
        "path": "/password",
        "value": "a"
    }
]
```

request failing (the connection timesout as the body is never received by the server):
```
PATCH /v1/users/2628258159781393046 HTTP/1.1
Referer: https://127.0.0.1/
Content-Type: application/json
session: Y2I7WaNHbYgycLM1FDHXsB66RNy6A9tX
Accept: application/json
Accept-Language: en-GB
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: 127.0.0.1
Content-Length: 175
Connection: close
Cache-Control: no-cache
Cookie: Tw0OlNAKsq9Qc6g5XMfJduBEn9iKDACh=session

```

**Comment by mislav** [comment]
I can't reproduce this with a newer version of IE 11. You might work around your problem by applying some updates to your Windows system.

Also, if this is really a bug with how IE 11 handles PATCH requests in its XMLHttpRequest implementation, then we can't do anything to fix this from the fetch polyfill, since we're relying on a non-broken XMLHttpRequest. If your problem persists, you might want to change the requests you're making from PATCH to POST.
