### ISSUE TITLE
Request fails NTML authentication after successful CORS preflight (IE11)

### ISSUE THREAD

**Issue by tlycken** [github/fetch#589]
We have a web application that talks to an API hosted on a different domain, using this library to polyfill `fetch` in order to support IE11. Since the backend is on a different domain, we have configured all the appropriate CORS headers.

When opening the app in e.g. Chrome, everything works smoothly. However, when browsing with IE11, we get a bunch of `401 Unauthorized` responses from the backend. On closer inspection, I can see that for each API call, the following happens:

1. A CORS preflight request (`OPTIONS`) is sent to the endpoint, with a successful response including all the required headers:

       Access-Control-Allow-Credentials: true
       Access-Control-Allow-Headers: accept,content-type
       Access-Control-Allow-Methods: GET
       Access-Control-Allow-Origin: http://localhost:8080

2. A `GET` request to the endpoint returns a `401 Unauthorized` response with

       WWW-Authenticate: Negotiate, NTLM

3. In Chrome, the browser pops up a dialog where I enter username and password, and then proceeds to negotiate the login and issue the request again, this time successfully (and this is the only thing I see in the network tab in Chrome DevTools).

4. In IE11, no username/password dialog pops up, and no negotiation takes place. Instead, I just get the bare `401` response.

Is there something I need to do with this polyfill in order to make it work with NTLM handshakes?

**Comment by dgraham** [comment]
While I'm not familiar with NTLM, this could have something to do with the [`withCredentials`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) setting on the cross-origin request. See the [cookies section](https://github.com/github/fetch#sending-cookies) of the documentation for an example enabling `withCredentials`.

Here's where we [toggle the setting](https://github.com/github/fetch/blob/7a692dc519a3a110526a26c7e252f99991510c2a/fetch.js#L448-L452) on the XMLHttpRequest object based on the configuration options passed into the `fetch` call. The browser coordinates the authentication steps, without exposing them via XMLHttpRequest, so this is as much control as we have.

You might try making the request with XMLHttpRequest, rather than fetch, to debug the issue. Removing the fetch wrapper layer will simplify testing the request and response.
