### ISSUE TITLE
safari v11.1 doesn't support for abort

### ISSUE THREAD

**Issue by ziweiZhang** [github/fetch#650]

**Comment by mislav** [comment]
That is true. Safari 11.1 implements `window.fetch` but doesn't implement the abort functionality which was added to the Fetch Standard relatively recently.

If you want to raise issues about Safari's implementation of `fetch`, please do so with the Safari team at Apple, and not here. Thank you!

Closing since there's nothing left that seems actionable for us from your original issue description.
