### ISSUE TITLE
Fetch doesn't respect mode: "same-origin"

### ISSUE THREAD

**Issue by motiz88** [github/fetch#661]
[Per the Fetch spec](https://fetch.spec.whatwg.org/#concept-request-mode),

> A request has an associated **mode**. [...] `"same-origin"` [is used] to ensure requests are made to same-origin URLs. Fetch will return a network error if the request is not made to a same-origin URL.

It appears that the polyfill doesn't enforce this. I have created a [test page](https://codesandbox.io/s/5xl01z0l0n) to demonstrate this issue, and how behaviour differs between the native implementation (tested on Chrome) and the polyfill.

I believe it's possible to emulate this on top of XHR by inspecting the various origins at the right times. I'd be happy to dive into the spec and work on a PR (some time in the next few weeks) if a maintainer here signals interest in landing such a change.

**Comment by mislav** [comment]
Yes, [we don't support `same-origin`](https://github.github.io/fetch/#caveats).

Even though it could technically be possible to emulate some of these features, such as `credentials: 'same-origin'` or `cache: '...'` directives, we choose _not_ to support them because it would inflate the size of this polyfill and make it difficult to test and maintain.

This polyfill never aimed to implement the entire spec; just the parts that cover 80% of all use-cases.

**Comment by mislav** [comment]
> Respectfully, can I ask that you make this stance clearer and more consistent in your documentation?

For sure! I just pushed some clarifications.

> make it seem like the criteria for a feature's inclusion are based more on it being _feasible_ (and spec-compliant)

Definitely; feasibility (as evident by size and maintainability of implementation) is our main criteria.

> covering "80% of all use-cases" (according to whom?)

80/20 is an expression rather than a statistic.

> Especially when I was offering to do the work.

And we're thankful for the offer! But we also need to be mindful that everything we accept, we will probably need to maintain for years to come. And personally, I'm wary of maintaing security features that are supposed to be browser internals.

**Comment by e955** [comment]
Aide
