### ISSUE TITLE
cdnjs v3.0.0 also not working

### ISSUE THREAD

**Issue by ayumihamsaki** [github/fetch#665]
Just to let you know the cdnjs also doesn't work when testing it on google canary Version 71.0.3568.1

The error in google canary is this for ref:

`Uncaught SyntaxError: Unexpected token export`

**Comment by mislav** [comment]
Sorry, we don't maintain cdnjs ourselves. You should take it with an issue or PR in their repo: see https://github.com/cdnjs/cdnjs/commit/6ec3f61b0930caebbd82cdfece6c9031bd545dc5 for starting point. See https://github.com/github/fetch/issues/656#issuecomment-425753336 and prior discussion for more info about why cdnjs likely wants to pull in `dist/fetch.umd.js` file instead of `fetch.js`.

Thank you for reporting!
