### ISSUE TITLE
Special Version to Work in Most Browsers?

### ISSUE THREAD

**Issue by machineghost** [github/fetch#670]
It seems this project has decided to make the main branch not support the majority of browsers, and require the use of a special (umd) branch.

I very much appreciate all the hard work you've done on this polyfill, so PLEASE don't take this the wrong way (I mean it as a genuine question), but ... isn't that bass ackwards?

The _entire_ point of a polyfill is that it's designed to fix old browsers, which means the entire point of using a polyfill is to use it _in old browsers_.  This is a polyfill library, so it seems odd that you would need a special branch just to use the polyfill in its intended use (to support old browsers).

Now just to be clear, I'm not saying anything against having multiple versions: I'm just referring to the library's choice to use a special case (new browsers? node?) for the _main_ branch, and require a special branch for the primary use case (old browsers).

And before you say something like "stop being a baby and just use the UMD version", this decision has real world consequences.  There is no working `fetch` polyfill on CDNJS currently because of this choice.

**Comment by mislav** [comment]
Hi, thanks for raising your concerns. I'm not sure what you refer to by the “umd branch”, or what your actual problem is, but here are some of my thoughts on the matter.

The way that we imagine our users bundle the polyfill in their project is:

1. `npm i whatwg-fetch`
2. `import "whatwg-fetch"` or `require("whatwg-fetch")` (in project code)

What then hopefully happens is that the project's asset bundler:
1. loads `node_modules/whatwg-fetch/package.json`,
1. reads the `main` property,
1. bundles the JS file referenced by the `main` property.

In whatwg-fetch 2.x, it was `main: "./fetch.js"`.
In v3.x it is `main: "./dist/fetch.umd.js"`.

The result of importing v2.x `fetch.js` and v3.x `dist/fetch.umd.js` is identical: **`window.fetch` will be polyfilled if missing.**

It might be that your asset bundler doesn't respect the `main` property of `package.json`. That is fine. This is why we incremented the major version number, which indicates that there might be breaking changes between v2.x and v3.x. If people were manually loading `whatwg-fetch/fetch.js` in their projects, now they have to:

* switch to loading `whatwg-fetch/dist/fetch.umd.js`, *or*
* simply continue using v2.x.

Now that I've elaborated on this, let's go back to your original issue:

* What exactly have you tried so far and in which way did it not work?
* Is there something forcing you to upgrade to v3.x before you're ready to do it? Is there something preventing you from sticking with v2.x?
* What is that you're expecting us to do, exactly?

Thank you!

**Comment by machineghost** [comment]
I definitely should have been clearer; my apologies.  This is the problem:

>In whatwg-fetch 2.x, it was main: "./fetch.js".
>In v3.x it is main: "./dist/fetch.umd.js".

You *could* have made `fetch.js` continue to be the main file, but instead you made fetch.js incompatible with old browsers, and made the new `fetch.umd.js`.  As I said before, the default use case of a polyfill is to support old browsers, not Node, so by making this change you've effectively thrown browser-users under the bus.

As a result, there is no working fetch polyfill on CDNJS right now.  They do the logical thing and serve `fetch.js` (https://cdnjs.cloudflare.com/ajax/libs/fetch/3.0.0/fetch.js).  This library making "using a polyfill for backwards compatibility" the special case is the problem.
