### ISSUE TITLE
DELETE with body

### ISSUE THREAD

**Issue by Dinodanio** [github/fetch#675]
If i use the delete method i want to set a body to give the server additional informations. But if i do it like this: 
```
fetch("", {
    method: "delete",
    body: body
})
```
my response is 400. 

If i look in the RFC 7231 specs the delete method can include a body. So is this a problem with fetch or with my nginx?

**Comment by keithamus** [comment]
Hey @Dinodanio thanks for the issue.

The code you have above looks fine. Without a more detailed reproduction of the issue I'm not sure we'll be able to help you much. If you're getting a `400` error I'd hazard a guess that your server is rejecting your input for some other reasons - maybe it expected an `Accept` header or something?

You'd have much more success posting your question to [Stack Overflow](https://stackoverflow.com/). It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within this polyfill. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
