### ISSUE TITLE
fetch() function returns an 'Failed to fetch' error after network change while server successfully process the request

### ISSUE THREAD

**Issue by csunmitel** [github/fetch#677]
We use a fetch() function to send a request to server. Request was queued before send to the server. Once the request is sent, we will wait for the success response from fetch() function to remove the item from the queue and process next.

Mostly it's working fine, however, if the network has some issues (not stable), the fetch() function will only returns error instead of correct server response. 

The step to reproduce the issue
1. use fetch() to send a request to server
2. after send the request and before receive the response, switch network.
3. In this case, the fetch() function will return a 'Failed to fetch' error. 
4. The the truth is the server already process the request successfully. 
5. Since we received an error, we will process the same request again, which cause issue.

I have searched on the web it seems more people experience it.
https://stackoverflow.com/questions/50418737/fetch-throws-typeerror-failed-to-fetch-for-successful-same-origin-request

This is not a cross domain issue (mode: cors) . It's more of a timing issue on the fetch side. Please help to provide a way so we can process the request correctly.

**Comment by mislav** [comment]
You sound like you're having problems with your browser's implementation of `fetch`, not with this polyfill. This issue tracker is only for the polyfill.

In any case, we couldn't fix this from the polyfill either, because how the browser handles connections and network changes is up to the browswers, and not something that can be affected through code.
