### ISSUE TITLE
Code samples should not use ES6 language features

### ISSUE THREAD

**Issue by hempels** [github/fetch#735]
README.md has several code samples which will not run on many of the browsers this polyfill is meant to support.
Specific examples include the `const` keyword and `import` statements.

**Comment by Simonwep** [comment]
You're probably gonna bundle your stuff with webpack anyway, using `const` and `import` is considered best practice and JS Standart.

**Comment by hempels** [comment]
Uh, well - we don't bundle our stuff with webpack. And const and import may be ES6 standard but ES6 is not supported by the browsers that this library primarily targets.

**Comment by Simonwep** [comment]
I just think these are still just _examples_, they don't tell how you'd need to do it - but I generally prefer if, even in such a case, best-practice is used. 
And a quite large amount people are using bundlers (In which, among your code, the polyfills get shipped). And they only provide the _tools_ you can use to create an Application - they don't tell you how and with with JS Version you _actually_ should write your code.
And polyfills are mainly made to actually get to use nextjs features.

I'd rather open an issue since they mix `var` and `const` in their README and `var` is by far "deprecated".

**Comment by dgraham** [comment]
We need to use `import` to document how to import the files into an application that is being bundled by webpack or rollup.

For applications that don't use bundling, the import section of the documentation can be ignored. You can simply refer to the compiled fetch file under `dist/` in a `<script>` tag or concatenate the file into your application's main `.js` file.
