### ISSUE TITLE
fetch.umd.js

### ISSUE THREAD

**Issue by kiquenet** [github/fetch#976]
Where is the file fetch.umd.js ? not in source.zip in Releases.

How-to use pollyfill without npm, only use script tag and js files.

**Comment by Nicholas-Westby** [comment]
Looks like this is missing again from the latest few releases. I was able to figure out how to get it thanks to this previous similar issue: https://github.com/github/fetch/issues/819

In short, you can get it from here: https://unpkg.com/whatwg-fetch@3.6.2/dist/fetch.umd.js

I suppose this should be considered a bug that could be fixed in one of two ways:

* Draft a release with the `fetch.umd.js` file.
* Update the README to link to unpkg so people know where to get the file.
